apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: curl
spec:
  containers:
  - command:
    - sleep
    - "5000"
    image: byrnedo/alpine-curl:latest
    imagePullPolicy: Always
    name: alpine-curl
