apiVersion: apps/v1
kind: DaemonSet 
metadata:
  name: ds-one
  labels:
    app: myapp
    type: front-end
spec:
  selector:
    matchLabels:
      system: DaemonSetOne 
  template:
    metadata:
      name: myapp-pod
      labels:
        system: DaemonSetOne
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.9.2

